### ISSUE TITLE
Add `bittorrent-lsd` to the `webtorrent` npm organization

### ISSUE THREAD

**Issue by feross** [webtorrent/bittorrent-lsd#1]
Can you add `bittorrent-lsd` to the `webtorrent` npm organization? I think you can click "Add Package" on this page to do it: https://www.npmjs.com/settings/webtorrent/packages

_Originally posted by @feross in https://github.com/webtorrent/torrent-discovery/pull/48#issuecomment-722649445_

**Comment by hicom150** [comment]
I think I've correctly added the package to the organization 👍
If you see something is missing or incorrect, just let me know 😉

**Comment by feross** [comment]
Looks good to me!
