### ISSUE TITLE
GitHub tag v1.0.0 and npm version is 1.0.0 but `package.json` is 0.1.0

### ISSUE THREAD

**Issue by feross** [webtorrent/bittorrent-lsd#4]
I noticed that there is a GitHub tag for v1.0.0 and the npm version is 1.0.0 but `package.json` is 0.1.0.

@hicom150 Curious how this happened. Should we just bump `package.json` to 1.0.0 to match what is already on npm? Then the next version can be 1.0.1, etc.

**Comment by hicom150** [comment]
I don't know what happened exactly but it was my bad, sorry 😅
I hope I fixed this issue in #5

**Comment by feross** [comment]
Fixed by #5
